apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  serviceAccountName: my-sa
  containers:
  - name: test-debug
    image: localhost:5000/sample-k8s-client-debug:0.0.1
    ports:
    - containerPort: 8090
    imagePullPolicy: Always
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
